### ISSUE TITLE
add "add post" UI to newPost page

### ISSUE THREAD

**Issue by shunei4517** [shunei4517/react-ts-tutorial#5]
# requirements
- user can create post like decorating greeting card
- user can put more than 1 pic to their card
- user can add description, tags, location, with whom

# directory
- newPost/

# tasks
- [ ] add card to page
- [ ] add text fields for items listed above
- [ ] add image to card
- [ ] add image input function 
- [ ] add post button and send to firestore
